### ISSUE TITLE
CSV文本格式问题

### ISSUE THREAD

**Issue by chrisli30** [huhu2356/coin-distribution#3]
我截了文件的前两行，既然都用下划线的表示方式，就所有的域都用
1. totalCoins -> coin_total
1. 为什么有leftCoin，所有的域都是0，这个是为了存到下次分配用？多出来的不是会再分配吗？既然这个域不会有很多，我们在输出文件里去掉，不要这个域了
1. 为什么所有的string类型都是这样的，"=""59osq"""，应该是"59osq"，你代码是不是每个string还包含了双引号？

"=""id""","=""name""","=""totalCoins""","=""comment_created_given""","=""story_voted_given""","=""story_visit_given""","=""story_shared_given""","=""story_created_given""","=""comment_created_received""","=""story_voted_received""","=""story_visit_received""","=""story_shared_received""","=""story_created_received""","=""leftCoin"""
"=""59osq""",,28796.1,0,59.53,42.45,1934.85,6531.53,1682.39,7032.43,3096.29,8416.63,0,0

**Comment by huhu2356** [comment]
leftCoin 是多出来存到下次分配用，那我去掉好了；

多包含一个string，是转化的时候 多加了参数 excelStrings，避免 excel 工具打开 output.csv 文件的时候 显示不正确；

**Comment by chrisli30** [comment]
okay, 改的没问题， closing this.
